global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "server"
    static_configs:
      - targets: ["nginx:443"]   # <-- Scrape metrics through Nginx
    metrics_path: /api/metrics  # <-- matches Nginx proxy path
    scheme: https                # <-- if Nginx serves HTTPS
    tls_config:
      insecure_skip_verify: true # <-- ignore self-signed SSL

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      # path_prefix: /api/alertmanager

rule_files:
  - "alert_rules.yml"