# kibana/config/kibana.yml

server.name: kibana
server.host: "0.0.0.0"

# ---- Connect to Elasticsearch over HTTPS ----
elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_PASSWORD}"

elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca/ca.crt"]
elasticsearch.ssl.verificationMode: full

# ---- Security ----
xpack.security.enabled: true
