server.name: kibana
server.host: "0.0.0.0"

elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "${KIBANA_SYSTEM_PASSWORD}"

server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key

elasticsearch.ssl.certificateAuthorities:
  - /usr/share/kibana/config/certs/ca/ca.crt

elasticsearch.ssl.verificationMode: full

xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}

server.basePath: "/kibana"
server.rewriteBasePath: true
