cluster.name: docker-cluster
node.name: elasticsearch
network.host: 0.0.0.0

xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

discovery.type: single-node
xpack.license.self_generated.type: basic
